import { Flavor } from "./types";

export const FLAVORS: Flavor[] = [
  {
    id: 0,
    name: "ORIGINAL",
    color: "#EF4444", // Red
    glowColor: "rgba(239, 68, 68, 0.4)",
    bgGradient: "from-red-950/40 to-stone-950",
    price: 3.99,
    tagline: "Timeless taste. Bold and refreshing.",
    desc: "The original recipe, crafted with natural spring water, pure cane sugar elements, and our signature botanicals, perfected for the modern sophisticated palate.",
    image: "/src/assets/images/finoka_original_bottle_transparent.webp",
    nutrition: {
      calories: 45,
      carbs: "11g",
      sodium: "15mg",
      sweetness: 4,
      fruitIntensity: 2,
      carbonation: 5,
    },
    ingredients: ["Volcanic Spring Water", "Pure Cane Sugar", "Signature Botanicals", "Citric Acid", "Natural Carbonation"],
    benefits: ["100% Organic Extracts", "Rich in Natural Minerals", "No Preservatives", "Sustainably Sourced"],
  },
  {
    id: 1,
    name: "LEMON LIME",
    color: "#22C55E", // Lime Green
    glowColor: "rgba(34, 197, 94, 0.4)",
    bgGradient: "from-green-950/40 to-stone-950",
    price: 4.25,
    tagline: "Zesty citrus fusion.",
    desc: "An electrifying blend of hand-picked Sicilian lemons and Persian limes. A crisp, tart explosion of clean citrus from sun-drenched groves.",
    image: "/src/assets/images/finoka_lemon_bottle_transparent.webp",
    nutrition: {
      calories: 35,
      carbs: "9g",
      sodium: "10mg",
      sweetness: 3,
      fruitIntensity: 5,
      carbonation: 4,
    },
    ingredients: ["Volcanic Spring Water", "Organic Stevia Leaf", "Sicilian Lemon Oil", "Key Lime Extract", "Natural Minerals"],
    benefits: ["Zero Added Sugars", "High Electrolytes", "Vitamins C & B6", "Anti-inflammatory Properties"],
  },
  {
    id: 2,
    name: "BERRY BLAST",
    color: "#A855F7", // Purple
    glowColor: "rgba(168, 85, 247, 0.4)",
    bgGradient: "from-purple-950/40 to-stone-950",
    price: 4.50,
    tagline: "Wild forest berry medley.",
    desc: "A deep, mystical fusion of wild blackberries, deep blue huckleberries, and ripe mountain raspberries. Intense, rich, and perfectly balanced darkness.",
    image: "/src/assets/images/finoka_berry_bottle_transparent.webp",
    nutrition: {
      calories: 48,
      carbs: "12g",
      sodium: "12mg",
      sweetness: 5,
      fruitIntensity: 4,
      carbonation: 3,
    },
    ingredients: ["Volcanic Spring Water", "Wild Huckleberry Essence", "Blackberry Puree", "Mountain Raspberry Extract", "Natural Stevia"],
    benefits: ["Antioxidant Rich", "Pure Superfood Extracts", "No Artificial Dye", "Supports Immune Health"],
  },
  {
    id: 3,
    name: "ORANGE RUSH",
    color: "#F97316", // Orange
    glowColor: "rgba(249, 115, 22, 0.4)",
    bgGradient: "from-orange-950/40 to-stone-950",
    price: 4.25,
    tagline: "Concentrated solar energy.",
    desc: "Vivid blood orange notes balanced with mandarin zests and a sophisticated, slightly bitter botanical finish. Pure carbonated sunshine.",
    image: "/src/assets/images/finoka_orange_bottle_transparent.webp",
    nutrition: {
      calories: 42,
      carbs: "10g",
      sodium: "14mg",
      sweetness: 4,
      fruitIntensity: 4,
      carbonation: 5,
    },
    ingredients: ["Volcanic Spring Water", "Blood Orange Infusion", "Mandarin Zest Extract", "Gentian Root Botanical", "Organic Agave"],
    benefits: ["Packed with Vitamin C", "Complex Citrus Terpenes", "Sustainable Agriculture", "Natural Energy Boost"],
  },
  {
    id: 4,
    name: "BLUE ICE",
    color: "#06B6D4", // Teal Blue
    glowColor: "rgba(6, 182, 212, 0.4)",
    bgGradient: "from-cyan-950/40 to-stone-950",
    price: 4.50,
    tagline: "Glacial cooling meets arctic blue.",
    desc: "The ultimate pure thirst quencher, combining mountain blueberries with a crisp arctic cooling finish. Delivers an immediate revitalizing chill effect.",
    image: "/src/assets/images/finoka_blue_bottle_transparent.webp",
    nutrition: {
      calories: 38,
      carbs: "9g",
      sodium: "20mg",
      sweetness: 2,
      fruitIntensity: 3,
      carbonation: 4,
    },
    ingredients: ["Volcanic Spring Water", "Arctic Blueberry Juice", "Mint Botanical Extract", "Electrolyte Blend", "L-Theanine"],
    benefits: ["Focus & Clarity Boost", "Superior Hydration", "Calms Tension", "Naturally Ionized"],
  },
];
